### ISSUE TITLE
SEC-3154: Repeated "Skip invoking on" logs with no content

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3364]
[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer) (Migrated from [SEC-3154](https://jira.spring.io/browse/SEC-3154?redirect=false)) said:

When I log onto a failry vanilla Boot app with DEBUG logging on I get a large number of these log entries:

``` 
2015-11-16 15:05:15.200 DEBUG 6609 --- [nio-8080-exec-4] tRepository$SaveToSessionResponseWrapper : Skip invoking on
``` 

with no further information. One would be enough, or else some more information to see what is being skipped, assuming it's actually different on each line.

**Comment by rwinch** [comment]
Fixed via d0dc47cb66bd798d67f57ab2444d14c6ecb79229

**Comment by sirianni** [comment]
I am still seeing this behavior in Spring Session 1.2.2.  The referenced commit removes the offending log message from Spring *Security's* `OnCommittedResponseWrapper`.  However, Spring Session has its own `OnCommittedResponseWrapper` which still has the log message.

**Comment by vpavic** [comment]
@sirianni I've opened spring-projects/spring-session#734 to discuss/address this in Spring Session.
