### ISSUE TITLE
Remove invalid ` from documentation

### ISSUE THREAD

**Issue by chaitanyathengdi** [spring-projects/spring-security#3751]
The Spring Security 3.2.x FAQ document(http://docs.spring.io/spring-security/site/docs/3.2.x/reference/htmlsingle/faq.html) has this error: 
Highlighted entries, such as `AccessDecisionVoter` go all the way to the end of the line, erroneously spanning several tens of words.

This issue is currently in 2 locations, in sections 2.16 and 3.3.

**Comment by rwinch** [comment]
@chaitanyathengdi Thanks for the report! This is now fixed in master

**Comment by chaitanyathengdi** [comment]
Sorry, not fixed yet: http://i.imgur.com/FXOordT.png http://i.imgur.com/jC246sl.png

**Comment by chaitanyathengdi** [comment]
Error seems to be on lines 231 and 268, with the words in issue having two backticks instead of one.

**Comment by rwinch** [comment]
@chaitanyathengdi Thanks for the review. The double backticks are deliberate and this is what fixes the issue.

I'm guessing you might be looking at an old version of the FAQ. You can find the updated version [here](http://docs.spring.io/spring-security/site/docs/4.1.0.BUILD-SNAPSHOT/reference/htmlsingle/#appendix-faq-method-security-in-web-context). Please let me know if you see any additional problems with this version. Once we release, then the changes will be reflected in the main site.
