### ISSUE TITLE
WebSocketSession#getHandshakeInfo#getPrincipal returns empty Mono even the user has authenticated

### ISSUE THREAD

**Issue by unlimitedsola** [spring-projects/spring-security#6028]
### Summary

I think this should be a regression issue, I found this when I upgraded my Spring Boot from 2.0.5 to 2.0.6.

When I subscribe `WebSocketSession#getHandshakeInfo#getPrincipal`,
it always returns an empty `Mono`
even the request has already authenticated.

### Actual Behavior

An empty `Mono` is returned.

### Expected Behavior

Should return a `Mono` that publishes exchange's principal
(like what we were getting in Spring Boot 2.0.5)

### Configuration

Please check the demo project below.

### Version

Spring Boot 2.0.6.RELEASE

### Sample

I've created a demo project for this issue:
https://github.com/unlimitedsola/spring-security-regression-issue-empty-principal

I also created a branch named `2.0.5` to prove it did work on Spring Boot 2.0.5.

**Comment by rwinch** [comment]
It seems like this is actually a reactor issue. Updating to Bisumuth-SR13 fixes it. See https://github.com/unlimitedsola/spring-security-regression-issue-empty-principal/pull/1

I'm working with @smaldini on why it fixes it.

**Comment by rwinch** [comment]
I have produced a version of the code that replicates the problem without Spring Security https://github.com/rwinch/spring-security-regression-issue-empty-principal/tree/no-security

**Comment by unlimitedsola** [comment]
Thanks for your investigation! going to update to Bisumuth-SR13 to workaround this.

**Comment by rwinch** [comment]
@unlimitedsola It appears that it might not actually fix the problem. It was pointed out to me that while the test passes, the logs still indicate that the principal is empty. At the moment it seems that a downgrade is necessary to fix it.

I'm still coordinating with the Reactor team, but in the meantime here is some work on the Reactor side to look into a fix https://github.com/reactor/reactor-netty/pull/489

**Comment by rwinch** [comment]
Closing this as it was fixed in Reactor via https://github.com/reactor/reactor-netty/pull/489

**Comment by rwinch** [comment]
@unlimitedsola Can you try the latest `Bisumuth-BUILD-SNAPSHOT` to confirm that this works for you and post the results on the above PR?

**Comment by unlimitedsola** [comment]
@rwinch sorry for late reply, I found that this issue is still reproducible in Spring Boot 2.1.0, which uses 0.8.x version of reactor-netty.

**Comment by unlimitedsola** [comment]
I've created a new branch `2.1.0` to prove: https://github.com/unlimitedsola/spring-security-regression-issue-empty-principal

**Comment by rwinch** [comment]
Thanks for the follow up @unlimitedsola 

> I've created a new branch 2.1.0 to prove: https://github.com/unlimitedsola/spring-security-regression-issue-empty-principal

I don't expect that your branch would work. You need to use`ext['reactor-bom.version'] = 'Californium-BUILD-SNAPSHOT'`.

> Also reproducible from your fork at no-security-boot-2.1 branch (which uses the latest snapshot version of reactor release train)

My branch works for me and on [Travis](https://travis-ci.com/rwinch/spring-security-regression-issue-empty-principal/builds/91259387).

Your branch using `ext['reactor-bom.version'] = 'Californium-BUILD-SNAPSHOT'` also works for me and [Travis](https://travis-ci.com/rwinch/spring-security-regression-issue-empty-principal/builds/91258985).

**Comment by unlimitedsola** [comment]
Thanks for your quick response, after running with `--refresh-dependencies`, the latest snapshot of reactor-netty worked for me. Sorry for disturb 😅

**Comment by rwinch** [comment]
@unlimitedsola No problem :smile:  I'm glad it is now working and thanks for following up so quickly
